export interface BingoTemplate {
  id: string;
  name: string;
  emoji: string;
  color: string;
  description: string;
  challenges: string[]; // exactly 24 — center (#12, index 12) is always FREE
}

export const TEMPLATES: BingoTemplate[] = [
  {
    id: "adventure",
    name: "Adventure Summer",
    emoji: "🏔️",
    color: "#FF6B5B",
    description: "For the bold ones who want to do it all.",
    challenges: [
      "Swim at sunrise",
      "Try street food",
      "Camp overnight",
      "Watch a meteor shower",
      "Learn to surf",
      "Go on a hike",
      "Read on the beach",
      "Cook a BBQ",
      "Rent a bike",
      "Watch the sunset",
      "Go kayaking",
      "Try a new sport",
      // index 12 = FREE (inserted by the board renderer)
      "Visit a waterfall",
      "Stargaze till 3am",
      "Go to a festival",
      "Swim in a river",
      "Try rock climbing",
      "Do a night hike",
      "Go paragliding",
      "Ride a horse",
      "Skinny dip",
      "Eat fruit straight from a tree",
      "Sleep under the stars",
      "Do a polar plunge",
    ],
  },
  {
    id: "chill",
    name: "Chill Summer",
    emoji: "🍦",
    color: "#2EC4B6",
    description: "Slow down, enjoy the little things.",
    challenges: [
      "Make homemade ice cream",
      "Read a whole book",
      "Have a picnic",
      "Watch 3 sunsets in a row",
      "Write in a journal",
      "Learn a new recipe",
      "Nap in a hammock",
      "Watch a classic film",
      "Visit a farmers market",
      "Bake something new",
      "Do a digital detox day",
      "Make a playlist",
      // FREE
      "Watch the sunrise",
      "Draw or paint outside",
      "Write letters to friends",
      "Try meditation",
      "Cook for someone",
      "Visit a museum",
      "Have breakfast in bed",
      "Learn card tricks",
      "Listen to a full album",
      "Go star-spotting",
      "Press flowers",
      "Make lemonade from scratch",
    ],
  },
  {
    id: "bishkek",
    name: "Local — Bishkek & Issyk-Kul",
    emoji: "🏞️",
    color: "#FFB347",
    description: "The ultimate Kyrgyz summer bucket list.",
    challenges: [
      "Swim in Issyk-Kul",
      "Eat samsa in Osh Bazaar",
      "Hike to a jailoo",
      "Ride a horse in the mountains",
      "Try kumiss for the first time",
      "Visit a yurt camp",
      "See Son-Kul lake",
      "Eat shashlik by a river",
      "Watch paragliders from Chunkurchak",
      "Drive the Chui valley",
      "Dip in a mountain spring",
      "Visit Burana Tower",
      // FREE
      "Eat a lagman in Karakol",
      "Attend a local wedding",
      "Buy felt slippers from a craftsman",
      "Hike Ala-Archa",
      "Watch the sunrise over the Tian Shan",
      "Find a hidden waterfall",
      "Night swim in the lake",
      "Try Dungan cuisine in Karakol",
      "Sleep in a yurt",
      "Drive to Barskoon waterfall",
      "Visit the Ruh Ordo complex",
      "Eat corn on the cob roadside",
    ],
  },
];
